djcrm/urls.py
"""
URL configuration for djcrm project.
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include
from leads.views import LandingPageView,SignupView

#GRUD+L Create, Retreive, Update and Delete + List

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(), name='landing-page'),
    path('leads/', include("leads.urls", namespace="leads")),
    path('agents/', include("agents.urls", namespace="agents")),
    path('signup/',SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name="reset-password"),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('login/',LoginView.as_view(), name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
"""
URL configuration for leads in djcrm project.

Here are all the urls related to this app LEADS
"""

from django.urls import path
from .views import (
    LeadListView, LeadDeleteView,
    LeadDetailView, LeadCreateView,LeadUpdateView,
    AssignAgentView,CategoryListView,CategoryDetailView,LeadCategoryUpdateView
)

app_name="leads" #an app name for leads

urlpatterns = [
    path('',LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/',LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/',LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/',LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-agent/',AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category/',LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('create/',LeadCreateView.as_view(), name='lead-create'),
    path('categories/',CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/',CategoryDetailView.as_view(), name='category-detail'),
]

leads/models.py
""" 
MODELS FOR LEADS APP
We will declare here every model we want to use in this project.

All models you known will be created in here
"""
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """Overiding user class"""
    is_organisor=models.BooleanField(default=True)
    is_agent=models.BooleanField(default=False)

class UserProfile(models.Model):
    """ 
    UserProfile Class it links to user which relates to an agentt o have control on the leads
    """
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username

class Lead(models.Model):
    """LEAD model for all of our leads"""
    first_name=models.CharField(max_length=20)
    last_name=models.CharField(max_length=20)
    age=models.IntegerField(default=0)
    organisation=models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    agent=models.ForeignKey("Agent",null=True, blank=True, on_delete=models.SET_NULL)
    category=models.ForeignKey("Category", related_name="leads", null=True, blank=True, on_delete=models.SET_NULL)
    description=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)
    phone_number=models.CharField(max_length=20)
    email=models.EmailField()
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"   

class Agent(models.Model):
    """ AGENT model for all of our agents """
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    organisation=models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    
    def __str__(self):
        # pylint: disable=no-member
        return self.user.email

class Category(models.Model):
    """ Class for category """
    name=models.CharField(max_length=30)
    organisation=models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    
    def __str__(self):
        """displaying category name"""
        return self.name

def post_user_created_signal(sender, instance, created,**kwargs):
    """ Posting Signal when ever created new user to get userprofile"""
    print(instance, created)
    if created:
        # pylint: disable=no-member
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_created_signal, sender=User)

leads/forms.py
"""
Here we will create most of the forms in LEADS App     
"""
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm,UsernameField
from .models import Lead,Agent

User=get_user_model()

class LeadModelForm(forms.ModelForm):
    """ 
    LeadModelForm 
    """
    class Meta:
        """ Meta Class for LeadModelForm """
        model=Lead
        fields=(
            'first_name',
            'last_name',
            'age',
            'agent',
            'description',
            'phone_number',
            'email',
        )

class LeadForm(forms.Form):
    """ 
    LeadForm
    """
    first_name=forms.CharField()
    last_name=forms.CharField()
    age=forms.IntegerField(min_value=0)
    
class CustomUserCreationForm(UserCreationForm):
    """ 
    Our Custum for user creation form
    """
    class Meta:
        """ Meta Class for our custom user creation form"""
        model=User
        fields=("username",)
        field_classes={"username": UsernameField}

class AssignAgentForm(forms.Form):
    """ AssignAgent form"""
    # pylint: disable=no-member
    agent=forms.ModelChoiceField(queryset=Agent.objects.none())
    
    def __init__(self, *args, **kwargs):
        request=kwargs.pop("request")
        agents=Agent.objects.filter(organisation=request.user.userprofile)
        super(AssignAgentForm,self).__init__(*args,**kwargs)
        self.fields["agent"].queryset=agents

class LeadCategoryUpdateForm(forms.ModelForm):
    """ModelForm for updating LeadCategory"""
    class Meta:
        """ Meta Class for LeadModelForm """
        model=Lead
        fields=(
            'category',
        )

leads/views.py
""" 
Views Module for Leads App
"""
from typing import Any
from django.core.mail import send_mail
from django.contrib.auth.forms import UserCreationForm
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.shortcuts import render,redirect,reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from agents.mixins import OrganisorAndLoginRequiredMixin
from .models import Lead,Agent, Category
from .forms import LeadModelForm,CustomUserCreationForm,AssignAgentForm,LeadCategoryUpdateForm

# Create your views here.
class SignupView(generic.CreateView):
    """ 
    CBV for Signup
    """
    template_name="registration/signup.html"
    form_class=CustomUserCreationForm
    
    def get_success_url(self):
        """ 
        Its ets back to the main view of the leads
        """
        return reverse ("login")

class LandingPageView(generic.TemplateView):
    """ 
    CBV for the hiome page of the system
    """
    template_name="landing.html"

class LeadListView(LoginRequiredMixin,generic.ListView):
    """ 
    CBV for displaying list of leads
    """
    template_name="leads/lead_list.html"
    context_object_name="leads"
    
    def get_queryset(self):
        user=self.request.user
        #initial queryset of leads for entire organisation
        if user.is_organisor:
            # pylint: disable=no-member
            queryset=Lead.objects.filter(
                organisation=user.userprofile, 
                agent__isnull=False
            )
        else:
            # pylint: disable=no-member
            queryset=Lead.objects.filter(
                organisation=user.agent.organisation, 
                agent__isnull=False
            )
            #filter for the agent who is logged int
            queryset=queryset.filter(agent__user=user)
        return queryset
    
    def get_context_data(self, **kwargs):
        user=self.request.user
        context=super(LeadListView, self).get_context_data(**kwargs)
        if user.is_organisor:
            # pylint: disable=no-member
            queryset=Lead.objects.filter(
                organisation=user.userprofile, 
                agent__isnull=True
            )
            context.update({
                "unassigned_leads":queryset
            })
        return context

class LeadDetailView(LoginRequiredMixin,generic.DetailView):
    """ 
    CBV for displaying a single lead
    """
    template_name="leads/lead_detail.html"
    context_object_name="lead"
    
    def get_queryset(self):
        user=self.request.user
        #initial queryset of leads for entire organisation
        if user.is_organisor:
            # pylint: disable=no-member
            queryset=Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset=Lead.objects.filter(organisation=user.agent.organisation)
            #filter for the agent who is logged int
            queryset=queryset.filter(agent__user=user)
        return queryset

class LeadCreateView(OrganisorAndLoginRequiredMixin,generic.CreateView):
    """ 
    CBV for creating a lead
    """
    template_name="leads/lead_create.html"
    form_class=LeadModelForm
    
    def get_success_url(self):
        """ 
        Its ets back to the main view of the leads
        """
        return reverse ("leads:lead-list")
    
    def form_valid(self,form):
        """ 
        Sending email
        """
        lead=form.save(commit=False)
        lead.organisation=self.request.user.userprofile
        lead.save()
        send_mail(
            subject="A lead has been created",
            message="Go to the side to see the new lead",
            from_email="test@test.com",
            recipient_list=["test@test.com"],
        )
        return super(LeadCreateView,self).form_valid(form)

class LeadUpdateView(OrganisorAndLoginRequiredMixin,generic.UpdateView):
    """ 
    CBV for updating a lead
    """
    template_name="leads/lead_update.html"
    form_class=LeadModelForm
    # pylint: disable=no-member
    def get_queryset(self):
        user=self.request.user
        #initial queryset of leads for entire organisation
        return Lead.objects.filter(organisation=user.userprofile)
    
    def get_success_url(self):
        """ 
        Its Sets back to the main view of the leads
        """
        return reverse ("leads:lead-list")

class LeadDeleteView(OrganisorAndLoginRequiredMixin,generic.DeleteView):
    """ 
    CBV for deleting a lead
    """
    template_name="leads/lead_delete.html"
    
    def get_success_url(self):
        """ 
        Its Sets back to the main view of the leads
        """
        return reverse ("leads:lead-list")

    def get_queryset(self):
        user=self.request.user
        # pylint: disable=no-member
        #initial queryset of leads for entire organisation
        return Lead.objects.filter(organisation=user.userprofile)

class AssignAgentView(OrganisorAndLoginRequiredMixin, generic.FormView):
    """ View for Assigning a lead to an agent"""
    template_name="leads/assign_agent.html"
    form_class=AssignAgentForm
        
    def get_form_kwargs(self,**kwargs):
        kwargs=super(AssignAgentView,self).get_form_kwargs(**kwargs)
            
        kwargs.update({
            "request": self.request
        })
        return kwargs
    
    def get_success_url(self):
        """ 
        Its Sets back to the main view of the leads
        """
        return reverse ("leads:lead-list")
    
    def form_valid(self, form):
        agent=form.cleaned_data["agent"]
        lead=Lead.objects.get(id=self.kwargs["pk"])
        lead.agent=agent
        lead.save()
        return super(AssignAgentView,self).form_valid(form)

class CategoryListView(LoginRequiredMixin, generic.ListView):
    """ 
    CBV for displaying Categories
    """
    template_name="leads/category_list.html"
    context_object_name="category_list"
    
    def get_context_data(self, **kwargs):
        context=super(CategoryListView, self).get_context_data(**kwargs)
        user=self.request.user
        
        if user.is_organisor:
            # pylint: disable=no-member
            queryset=Lead.objects.filter(
                organisation=user.userprofile, 
            )
        else:
            queryset=Lead.objects.filter(
                organisation=user.agent.organisation, 
            )
        
        context.update({
            "unassigned_lead_count":queryset.filter(category__isnull=True).count(),
            "converted_count":queryset.filter(category__name="Converted").count(),
            "contacted_count":queryset.filter(category__name="Contacted").count(),
            "unconverted_count":queryset.filter(category__name="Unconverted").count()
        })
        return context
    
    def get_queryset(self):
        user=self.request.user
        #initial queryset of leads for entire organisation
        if user.is_organisor:
            # pylint: disable=no-member
            queryset=Category.objects.filter(
                organisation=user.userprofile, 
            )
        else:
            queryset=Category.objects.filter(
                organisation=user.agent.organisation, 
            )
        return queryset

class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    """ SHowing up the leads of that category"""
    template_name="leads/category_detail.html"
    context_object_name="category"
    
    def get_queryset(self):
        user=self.request.user
        #initial queryset of leads for entire organisation
        if user.is_organisor:
            # pylint: disable=no-member
            queryset=Category.objects.filter(
                organisation=user.userprofile, 
            )
        else:
            queryset=Category.objects.filter(
                organisation=user.agent.organisation, 
            )
        return queryset

class LeadCategoryUpdateView(LoginRequiredMixin,generic.UpdateView):
    """CBV Updating the category of the lead they belong to"""
    template_name="leads/lead_category_update.html"
    form_class=LeadCategoryUpdateForm
    # pylint: disable=no-member
    def get_queryset(self):
        user=self.request.user
        #initial queryset of leads for entire organisation
        if user.is_organisor:
            # pylint: disable=no-member
            queryset=Lead.objects.filter(organisation=user.userprofile)
        else:
            queryset=Lead.objects.filter(organisation=user.agent.organisation)
            #filter for the agent who is logged int
            queryset=queryset.filter(agent__user=user)
        return queryset
    
    def get_success_url(self):
        """ 
        Its Sets back to the main view of the leads
        """
        return reverse ("leads:lead-detail", kwargs={"pk":self.get_object().id})
    

leads/templates/leads/assign_agent.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}
<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'leads:lead-list' %}">
        Go Back to Leads
    </a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-3xl text-gray-800">Assign an agent to this lead </h1>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md">Submit</button>
    </form>
</div>
{% endblock content %}

leads/templates/leads/category_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">
            {{ category.name }}
        </h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
            these are the leads under this category
        </p>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">
                    First Name
                </th>
                <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                    last Name
                </th>
             </tr>
          </thead>
          <tbody>
            <!-- We are looping throught all of this-->
            {% for lead in category.leads.all %}
                <tr>
                    <td class="px-4 py-3">
                        <a class="hover:text-blue-500" href="{% url 'leads:lead-detail' lead.pk %}">{{ lead.first_name }}</a>
                    </td>
                    <td class="px-4 py-3">{{ lead.last_name }}</td>
                </tr>
            {% empty %}
                <tr><td class="px-4 py-3">No data found.</td></tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
</section>

{% endblock content %}
    

leads/templates/leads/category_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Category</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">
            these categories segments the leads
        </p>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Lead Count</th>
             </tr>
          </thead>
          <tbody>
            <!-- We are looping throught all of this-->
            <tr>
                <td class="px-4 py-3">Unassigned</td>
                <td class="px-4 py-3">{{ unassigned_lead_count }}</td>
            </tr>
            {% for category in category_list %}
                <tr>
                    <td class="px-4 py-3">
                      <a href="{% url 'leads:category-detail' category.pk %}">{{ category.name }}</a>
                    </td>
                    {% if category.name == "Converted" %}
                      <td class="px-4 py-3">{{ converted_count }}</td>
                    {% elif category.name == "Contacted" %}
                      <td class="px-4 py-3">{{ contacted_count }}</td>
                    {% elif category.name == "Unconverted" %}
                      <td class="px-4 py-3">{{ unconverted_count }}</td>
                    {% endif %}
                </tr>
            {% empty %}
                <tr><td class="px-4 py-3">No categories found.</td></tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
</section>

{% endblock content %}
    

leads/templates/leads/lead_category_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
                    {{lead.first_name}} {{lead.last_name}}
                </h1>
                <div class="flex mb-4">
                    <a  href="{% url 'leads:lead-detail' lead.pk %}" 
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 text-center">
                        Overview
                    </a>
                    <a 
                        href="{% url 'leads:lead-category-update' lead.pk %}" 
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1  text-center bg-gray-300">
                        Category
                    </a>
                    <a  href="{% url 'leads:lead-update' lead.pk %}" 
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1  text-center">
                        Update Details
                    </a>
                </div>
                <!-- Update form will be there -->
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}                    
                    <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md">
                        Submit
                    </button>
                </form>
                <!-- end of the update form -->
            </div>
        </div>
    </div>
</section>
{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}}</h1>
                <div class="flex mb-4">
                    <a  href="'{% url 'leads:lead-detail' lead.pk %}'"
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1 text-center bg-gray-300">
                        Overview
                    </a>
                    <a  href="{% url 'leads:lead-category-update' lead.pk %}" 
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 text-center">
                        Category
                    </a>
                    <a  href="{% url 'leads:lead-update' lead.pk %}" 
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 text-center">
                        Update Details
                    </a>
                </div>
                <p class="leading-relaxed mb-4">
                    {{ lead.description}}
                </p>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Age</span>
                    <span class="ml-auto text-gray-900 font-semibold">{{ lead.age}}</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Email</span>
                    <span class="ml-auto text-gray-900 font-semibold">{{ lead.email}}</span>
                </div>
                <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                    <span class="text-gray-500">Cell Phone</span>
                    <span class="ml-auto text-gray-900 font-semibold">{{lead.phone_number}}</span>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

leads/templates/leads/lead_list.html
{% extends "base.html" %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Leads</h1>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:category-list' %}">
                    View categories
                </a>
            </div>
            {% if request.user.is_organisor %}
            <div>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:lead-create' %}">
                    Create a new Lead
                </a>
            </div>
            {% endif %}
        </div>
        <!-- Testing tabel -->
        <div class="w-full bg-gray-100 flex items-center justify-center ">
            <table class="min-w-full bg-white border border-gray-300 rounded-lg shadow-md">
                <thead class="bg-gray-200 text-black">
                    <tr>
                        <th class="text-left py-3 px-4 font-semibold text-sm">First Name</th>
                        <th class="text-left py-3 px-4 font-semibold text-sm">Last Name</th>
                        <th class="text-left py-3 px-4 font-semibold text-sm">Age</th>
                        <th class="text-left py-3 px-4 font-semibold text-sm">Email</th>
                        <th class="text-left py-3 px-4 font-semibold text-sm">Description</th>
                        <th class="text-left py-3 px-4 font-semibold text-sm">Cell Phone Number</th>
                        <th class="text-left py-3 px-4 font-semibold text-sm">Category</th>
                        <th class="text-left py-3 px-4 font-semibold text-sm">Action</th>
                    </tr>
                </thead>
                <tbody class="text-gray-700">
                    {% for lead in leads %}
                    <tr>
                        <td class="text-left py-3 px-4 font-semibold">{{lead.first_name}}</td>
                        <td class="text-left py-3 px-4 font-semibold">{{ lead.last_name}}</td>
                        <td class="text-left py-3 px-4">{{lead.age}}</td>
                        <td class="text-left py-3 px-4">{{lead.email}}</td>
                        <td class="text-left py-3 px-4">{{lead.description}}</td>
                        <td class="text-left py-3 px-4">{{lead.phone_number}}</td>
                        <td class="text-left py-3 px-4">
                            <span class="bg-green-200 text-green-600 py-1 px-3 rounded-full text-xs">{{lead.category}}</span>
                        </td>
                        <td class="text-left py-3 px-4">
                            <a href="{% url 'leads:lead-detail' lead.pk %}" class="bg-blue-500 text-white px-3 py-1 rounded text-xs font-medium">Edit</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- End of testing table-->

        <!-- Removed Code here, you can find at the note.txt file 'Displaying leads using content' -->

        <!-- Displaying unassigned leads-->
        {% if unassigned_leads.exists %}
            <div class="mt-5 flex flex-wrap -m-4">
                <div class="p-4 w-full">
                    <h1 class="text-4xl text-gray-800">Unassigned Leads</h1>
                </div>
                {% for lead in unassigned_leads %}
                <div class="p-4 lg:w-1/2 md:w-full">
                    <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                        <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                            </svg>
                        </div>
                        <div class="flex-grow">
                            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                                {{lead.first_name}} {{lead.last_name}}
                            </h2>
                            <p class="leading-relaxed text-base">
                                {{lead.description}}
                            </p>
                            <a href="{% url 'leads:assign-agent' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
                                Assig an agent
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endif %}
        <!-- the end of displaying unassigned leads-->
    </div>
</section>
{% endblock content %}

leads/templates/leads/lead_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
                    {{lead.first_name}} {{lead.last_name}}
                </h1>
                <div class="flex mb-4">
                    <a  href="{% url 'leads:lead-detail' lead.pk %}" 
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1  text-center">
                        Overview
                    </a>
                    <a 
                        href="{% url 'leads:lead-category-update' lead.pk %}" 
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1  text-center">
                        Category
                    </a>
                    <a  href="{% url 'leads:lead-update' lead.pk %}" 
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1  text-center bg-gray-300">
                        Update Details
                    </a>
                </div>
                <!-- Update form will be there -->
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md">
                        Submit
                    </button>
                </form>
                <!-- end of the update form -->
                <div class="mt-5 py-5 border-t border-gray-200">
                    <a href="{% url 'leads:lead-delete' lead.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                        Delete
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}