agents/urls.py
""" 
URL for the agents app will be defined here
"""
from django.urls import path
from.views import (
    AgentListView,AgentCreateView, 
    AgentDetailView,AgentUpdateView,AgentDeleteView
)

app_name = "agents"

urlpatterns = [
    path('',AgentListView.as_view(), name="agent-list"),
    path('<int:pk>/',AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/',AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/',AgentDeleteView.as_view(), name='agent-delete'),
    path('create/',AgentCreateView.as_view(), name="agent-create"),
]

djcrm/urls.py
"""
URL configuration for djcrm project.
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include
from leads.views import LandingPageView,SignupView

#GRUD+L Create, Retreive, Update and Delete + List

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(), name='landing-page'),
    path('leads/', include("leads.urls", namespace="leads")),
    path('agents/', include("agents.urls", namespace="agents")),
    path('signup/',SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name="reset-password"),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('login/',LoginView.as_view(), name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
""" 
FORMS.PY
this will hold any forms related spceially to this app [agents], its getting models from other apps in the project to fullfill ista operatins like Agnet class from leads module
"""
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User=get_user_model()

class AgentModelForm(forms.ModelForm):
    """ ModelForm for agent"""
    
    class Meta:
        model=User
        fields=(
            'email',
            'username',
            'first_name',
            'last_name'
        )

agents/views.py
""" 
Any VIEWS for agents app will defined here
"""
import random
from django.core.mail import send_mail
from django.views import generic    
#from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import reverse
from leads.models import Agent
from .forms import AgentModelForm
from .mixins import OrganisorAndLoginRequiredMixin

class AgentListView(OrganisorAndLoginRequiredMixin, generic.ListView):
    """ View for displaying list agents"""
    template_name="agents/agent_list.html"
    
    def get_queryset(self):
        """a get querryset for AgentListView() view """
        organisation=self.request.user.userprofile
        # pylint: disable=no-member
        return Agent.objects.filter(organisation=organisation)

class AgentCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    """ View for Creating new Agent"""
    template_name="agents/agent_create.html"
    form_class=AgentModelForm
    
    def get_success_url(self):
        """ returning to main page of this app"""
        return reverse("agents:agent-list")
    
    def form_valid(self, form):
        """ overiding form_valid() to enter the current user as the oganisation of th agent"""
        user=form.save(commit=False)
        user.is_agent=True
        user.is_organisor=False
        user.set_password(f"{random.randint(0,1000000)}")
        user.save()
        # pylint: disable=no-member
        Agent.objects.create(
            user=user,
            organisation=self.request.user.userprofile
        )
        
        send_mail(
            subject="You are invited to be an agent",
            message="You were added as an agent on DJCRM, please come login to start",
            from_email="admin@test.com",
            recipient_list=[user.email]
        )
        #agent.organisation=self.request.user.userprofile
        #agent.save()
        return super(AgentCreateView,self).form_valid(form)

class AgentDetailView(OrganisorAndLoginRequiredMixin,generic.DetailView):
    """VIEW for displaying the detail of an agent"""
    template_name="agents/agent_detail.html"
    context_object_name="agent"
    
    def get_queryset(self):
        """a get querryset for AgentListView() view """
        organisation=self.request.user.userprofile
        # pylint: disable=no-member
        return Agent.objects.filter(organisation=organisation)

class AgentUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    """ View for Creating new Agent"""
    template_name="agents/agent_update.html"
    form_class=AgentModelForm
    
    def get_success_url(self):
        """ returning to main page of this app"""
        return reverse("agents:agent-list")
    
    def get_queryset(self):
        """a get querryset for AgentListView() view """
        organisation=self.request.user.userprofile
        # pylint: disable=no-member
        return Agent.objects.filter(organisation=organisation)


class AgentDeleteView(OrganisorAndLoginRequiredMixin,generic.DeleteView):
    """VIEW for displaying the detail of an agent"""
    template_name="agents/agent_delete.html"
    context_object_name="agent"
    
    def get_success_url(self):
        """ returning to main page of this app"""
        return reverse("agents:agent-list")
    
    def get_queryset(self):
        """a get querryset for AgentListView() view """
        organisation=self.request.user.userprofile
        # pylint: disable=no-member
        return Agent.objects.filter(organisation=organisation)

agents/templates/agents/agent_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto">
    <div class="py-5 border-t border-gray-200">
        <a  class="hover:text-blue-500"
            href="{% url 'agents:agent-list' %}">
            <span class="bg-green-200 text-green-600 py-1 px-3 rounded-full text-xs mb-5 hover:text-blue-500">
                Go Back to Agents
            </span>
        </a>
    </div>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Creating new agent</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md">
            Submit
        </button>
    </form>
</div>
{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto">
    <div class="mt-5 py-5 border-b border-gray-200">
        <a class="hover:text-blue-500 " href="{% url 'agents:agent-list' %}">Go Back to Agents</a>
    </div>
    <h1 class="text-3xl text-gray-800">Are you sure you want to delete this agent </h1>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md">
            Submit
        </button>
    </form>
</div>
{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.username}}</h1>
                <div class="flex mb-4">
                    <a  href="{% url 'agents:agent-detail' agent.pk %}"
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1 text-center bg-gray-300">
                        Overview
                    </a>
                    <a  href="{% url 'agents:agent-update' agent.pk %}" 
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 text-center">
                        Update Details
                    </a>
                </div>
                <p class="leading-relaxed mb-4">
                   Here is the detail view of the {{agent.user.username}}.
                </p>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">First Name</span>
                    <span class="ml-auto text-gray-900 font-semibold">{{agent.user.first_name}}</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Last Name</span>
                    <span class="ml-auto text-gray-900 font-semibold">{{agent.user.last_name}}</span>
                </div>
                <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                    <span class="text-gray-500">Email</span>
                    <span class="ml-auto text-gray-900 font-semibold">{{agent.user.email}}</span>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Agents</h1>
            </div>
            <div>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'agents:agent-create' %}">Create a new Agent</a>
            </div>
        </div>  
        <div class="w-full bg-gray-100 flex items-center justify-center ">
            <table class="min-w-full bg-white border border-gray-300 rounded-lg shadow-md">
                <thead class="bg-gray-200 text-black">
                    <tr>
                        <th class="text-left py-3 px-4 font-semibold text-sm">First Name</th>
                        <th class="text-left py-3 px-4 font-semibold text-sm">Last Name</th>
                        <th class="text-left py-3 px-4 font-semibold text-sm">Username</th>
                        <th class="text-left py-3 px-4 font-semibold text-sm">Email</th>
                        <th class="text-left py-3 px-4 font-semibold text-sm">Action</th>
                    </tr>
                </thead>
                <tbody class="text-gray-700">
                    {% for agent in object_list %}
                    <tr>
                        <td class="text-left py-3 px-4">{{agent.user.first_name}}</td>
                        <td class="text-left py-3 px-4">{{agent.user.last_name}}</td>
                        <td class="text-left py-3 px-4">{{agent.user.username}}</td>
                        <td class="text-left py-3 px-4">{{agent.user.email}}</td>
                        <td class="text-left py-3 px-4">
                            <a href="{% url 'agents:agent-detail' agent.pk %}" class="bg-blue-500 text-white px-3 py-1 rounded text-xs font-medium">Edit</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- Remoced code was there, you can find at note.txt '' -->
    </div>
</section>
{% endblock content %}
    

agents/templates/agents/agent_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
                    {{agent.user.username}}
                </h1>
                <p>{{ form.non_field_errors }}</p>
                <div class="flex mb-4">
                    <a  href="{% url 'agents:agent-detail' agent.pk %}" 
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1 text-center">
                        Overview
                    </a>
                    <a  href="{% url 'agents:agent-update' agent.pk %}" 
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1 text-center bg-gray-300">
                        Update Details
                    </a>
                </div>
                <!-- Update form will be there -->
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md">
                        Submit
                    </button>
                </form>
                <!-- end of the update form -->
                <div class="mt-5 py-5 border-t border-gray-200">
                    <a  href="{% url 'agents:agent-delete' agent.pk %}" 
                        class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                        Delete
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}