agents/urls.py
""" 
URL for the agents app will be defined here
"""
from django.urls import path
from.views import (
    AgentListView,AgentCreateView, 
    AgentDetailView,AgentUpdateView,AgentDeleteView
)

app_name = "agents"

urlpatterns = [
    path('',AgentListView.as_view(), name="agent-list"),
    path('<int:pk>/',AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/',AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/',AgentDeleteView.as_view(), name='agent-delete'),
    path('create/',AgentCreateView.as_view(), name="agent-create"),
]

djcrm/urls.py
"""
URL configuration for djcrm project.
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include
from leads.views import LandingPageView,SignupView

#GRUD+L Create, Retreive, Update and Delete + List

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(), name='landing-page'),
    path('leads/', include("leads.urls", namespace="leads")),
    path('agents/', include("agents.urls", namespace="agents")),
    path('signup/',SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name="reset-password"),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('login/',LoginView.as_view(), name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
"""
URL configuration for leads in djcrm project.

Here are all the urls related to this app LEADS
"""

from django.urls import path
from .views import (
    LeadListView, LeadDeleteView,
    LeadDetailView, LeadCreateView,LeadUpdateView,
    AssignAgentView,CategoryListView,CategoryDetailView,LeadCategoryUpdateView
)

app_name="leads" #an app name for leads

urlpatterns = [
    path('',LeadListView.as_view(), name='lead-list'),
    path('<int:pk>/',LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/',LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/',LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-agent/',AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category/',LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('create/',LeadCreateView.as_view(), name='lead-create'),
    path('categories/',CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/',CategoryDetailView.as_view(), name='category-detail'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DJCRM</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <div class="max-w-7xl mx-auto">
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}
    </div>
    {% include 'scripts.html' %}
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            CRM Dashboard
        </h1>
    
        <div class="flex flex-wrap -m-4 text-center">
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ total_lead_count }}</h2>
                <p class="leading-relaxed">Total Leads</p>
                </div>
            </div>
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ total_in_past30 }}</h2>
                <p class="leading-relaxed">Leads added in last 30 days</p>
                </div>
            </div>
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ converted_in_past30 }}</h2>
                <p class="leading-relaxed">Converted in last 30 days</p>
                </div>
            </div>
        </div>
        
      </div>
    </div>
</section>
{% endblock content %}

templates/landing.html
{% extends "base.html" %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img 
        class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" 
        alt="hero" 
        src="static/images/sicon.png"
      >
      <div class="text-center lg:w-2/3 w-full ">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            CRM built with Django
        </h1>
        <p class="mb-8 leading-relaxed">
            This CRM helps you manage your leads
        </p>
        <div class="flex justify-center">
          {% if user.is_authenticated %}
            <a 
              href="{% url 'agents:agent-list' %}"
              class="ml-4 inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg ">
              GO to Agents List
            </a>
            &nbsp;&nbsp; <!-- Non-breaking space -->
            <a 
              href="{% url 'leads:lead-list' %}"
              class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
              Go to Leads list
            </a>
          {% endif %}
        </div>
      </div>
    </div>
</section>
{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font">
    <div 
      class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center border-b border-gray-200">
      <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <svg 
            id="Layer_1" 
            class="w-10 h-10" enable-background="new 0 0 512 512" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
            <g>
            <path 
              d="m186.399 126.224 21.036-8.981-.129-28.068-22.222-9.427c-1.83-5.848-4.299-11.552-7.406-17.002l9.004-22.615-20.015-19.837-22.655 9.086c-5.487-3.067-11.226-5.497-17.105-7.291l-9.577-22.089-28.177.015-8.908 21.001c-6.679 1.732-13.168 4.294-19.304 7.688l-20.938-8.344-19.832 19.858 8.483 20.815c-3.375 6.13-5.914 12.607-7.618 19.269l-21.036 8.981.129 28.068 22.222 9.427c1.83 5.848 4.299 11.552 7.406 17.002l-9.004 22.614 20.015 19.837 22.655-9.086c5.487 3.067 11.226 5.497 17.105 7.291l9.577 22.088 28.176-.015 8.908-21.001c6.679-1.731 13.168-4.294 19.304-7.688l20.938 8.344 19.832-19.858-8.483-20.814c3.376-6.129 5.915-12.606 7.619-19.268zm-53.932 4.742c-14.987 15.007-39.399 15.02-54.524.029-15.126-14.991-15.238-39.308-.25-54.315s39.399-15.019 54.524-.029c15.125 14.991 15.238 39.308.25 54.315z" fill="#a6f5cf"/>
            <path 
              d="m186.399 126.224 21.036-8.981-.129-28.068-22.222-9.427c-1.83-5.848-4.299-11.552-7.406-17.002l9.004-22.615-20.015-19.837-22.655 9.086c-5.487-3.067-11.226-5.497-17.105-7.291l-9.577-22.089-28.177.015-5.627 13.266c37.776 13.649 64.775 49.826 64.775 92.31 0 41.563-25.841 77.089-62.334 91.391l4.138 9.544 28.176-.015 8.908-21.001c6.679-1.731 13.168-4.294 19.304-7.688l20.938 8.344 19.832-19.858-8.483-20.815c3.376-6.13 5.915-12.607 7.619-19.269z" fill="#8aedbd"/><g><g>
            <path 
              d="m450.55 353.009h-389.1v-211.24c0-11.529 9.346-20.876 20.876-20.876h347.348c11.529 0 20.876 9.346 20.876 20.876z" fill="#6967bf"/>
            <path 
              d="m429.674 120.894h-41.207c11.529 0 20.876 9.346 20.876 20.876v211.24h41.207v-211.24c0-11.53-9.347-20.876-20.876-20.876z" fill="#5b59b2"/>
            <path 
              d="m478.423 391.106h-444.846c-11.529 0-20.876-9.346-20.876-20.876v-17.222h486.598v17.222c0 11.53-9.346 20.876-20.876 20.876z" fill="#7776d0"/>
            <path 
              d="m96.174 155.685h319.651v197.324h-319.651z" fill="#d4d9ff"/></g><g>
            <path 
              d="m362.479 312.618h-212.958c-13.11 0-23.738-10.628-23.738-23.738v-68.645c0-13.11 10.628-23.738 23.738-23.738h212.957c13.11 0 23.738 10.628 23.738 23.738v68.645c0 13.11-10.627 23.738-23.737 23.738z" fill="#fff5b5"/><g fill="#7776d0">
            <path 
              d="m360.579 282.73-11.221-58.719c-.823-4.041-4.273-7.026-8.389-7.259-4.122-.225-7.883 2.344-9.156 6.266-.029.089-.056.178-.082.268l-10.589 37.146-10.982-37.224c-.027-.093-.056-.186-.088-.277-1.315-3.909-5.095-6.455-9.224-6.169-4.115.278-7.532 3.301-8.326 7.436l-10.578 58.61c-.758 4.199 2.032 8.218 6.231 8.976 4.193.757 8.218-2.032 8.976-6.231l5.804-32.158 9.593 32.515c.027.092.056.184.087.275 1.246 3.709 4.703 6.192 8.613 6.192h.048c3.929-.02 7.382-2.545 8.595-6.282.029-.088.055-.177.081-.266l9.261-32.487 6.171 32.289c.801 4.193 4.857 6.938 9.039 6.139 4.19-.801 6.938-4.848 6.136-9.04z"/>
            <path 
              d="m213.027 270.237c-3.269-2.743-8.143-2.317-10.885.951-.521.621-1.079 1.198-1.663 1.717-2.994 2.667-6.822 4.019-11.377 4.019-12.333 0-22.366-10.034-22.366-22.367s10.033-22.367 22.366-22.367c4.483 0 8.806 1.319 12.501 3.815 3.536 2.388 8.339 1.459 10.727-2.077s1.459-8.339-2.077-10.727c-6.26-4.228-13.573-6.463-21.151-6.463-20.853 0-37.819 16.966-37.819 37.819s16.966 37.819 37.819 37.819c8.341 0 15.829-2.743 21.652-7.93 1.139-1.013 2.224-2.132 3.225-3.324 2.742-3.268 2.317-8.142-.952-10.885z"/>
            <path 
              d="m272.8 240.106c0-12.885-10.88-23.368-24.254-23.368h-15.993c-.003 0-.007 0-.01 0s-.007 0-.01 0c-4.268 0-7.726 3.459-7.726 7.726v60.186c0 4.267 3.459 7.726 7.726 7.726s7.726-3.459 7.726-7.726v-16.499l19.014 21.604c1.527 1.735 3.66 2.622 5.803 2.622 1.813 0 3.634-.634 5.102-1.927 3.203-2.819 3.514-7.701.695-10.904l-15.082-17.136c9.846-2.976 17.009-11.849 17.009-22.304zm-24.254 7.916c-1.922 0-5.149.013-8.199.028-.015-2.971-.028-6.092-.028-7.943 0-1.576-.008-4.8-.016-7.915h8.243c4.771 0 8.801 3.625 8.801 7.915s-4.03 7.915-8.801 7.915z"/></g></g></g><g>
            <path 
              d="m512 383.72c0-42.466-34.94-76.772-77.641-75.738-39.689.961-72.226 32.954-73.819 72.622-.833 20.748 6.693 39.723 19.472 53.864 4.524 5.006 6.955 11.542 6.728 18.29 0 17.935 14.539 32.474 32.474 32.474h34.047c17.935 0 32.474-14.539 32.474-32.474-.15-6.593 2.042-13.146 6.517-18.057 12.264-13.457 19.748-31.34 19.748-50.981z" fill="#ffd54d"/>
            <path 
              d="m512 383.72c0-42.466-34.94-76.772-77.641-75.738-6.448.156-12.708 1.132-18.676 2.826 31.805 8.99 55.11 38.23 55.11 72.912 0 19.641-7.484 37.524-19.746 50.981-4.474 4.91-6.666 11.464-6.517 18.057 0 16.725-12.644 30.497-28.894 32.279 1.176.129 2.37.196 3.58.196h34.047c17.935 0 32.474-14.539 32.474-32.474-.15-6.593 2.042-13.146 6.517-18.057 12.262-13.458 19.746-31.341 19.746-50.982z" fill="#ffc919"/>
            <path 
              d="m450.748 512h-29.019c-7.392 0-13.384-5.992-13.384-13.384 0-7.392 5.992-13.384 13.384-13.384h29.019c7.392 0 13.384 5.992 13.384 13.384 0 7.392-5.992 13.384-13.384 13.384z" fill="#7776d0"/>
            <path 
              d="m443.966 484.489v-70.02h15.56c4.268 0 7.726-3.459 7.726-7.726s-3.459-7.726-7.726-7.726h-46.574c-4.268 0-7.726 3.459-7.726 7.726s3.459 7.726 7.726 7.726h15.561v70.02z" fill="#fff"/></g><g fill="#e8f3ff">
            <path 
              d="m345.265 466.878c0-4.275 3.462-7.726 7.726-7.726 4.266 0 7.726 3.451 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.265 0-7.726-3.461-7.726-7.726zm-41.208 0c0-4.275 3.462-7.726 7.726-7.726 4.266 0 7.726 3.451 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.264 0-7.726-3.461-7.726-7.726zm-41.207 0c0-4.275 3.462-7.726 7.726-7.726 4.266 0 7.726 3.451 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.264 0-7.726-3.461-7.726-7.726zm-41.207 0c0-4.275 3.462-7.726 7.726-7.726 4.266 0 7.726 3.451 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.264 0-7.726-3.461-7.726-7.726zm-41.207 0c0-4.275 3.462-7.726 7.726-7.726 4.266 0 7.726 3.451 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.265 0-7.726-3.461-7.726-7.726zm-41.208 0c0-4.275 3.462-7.726 7.726-7.726 4.266 0 7.726 3.451 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.264 0-7.726-3.461-7.726-7.726zm-41.207 0c0-4.275 3.462-7.726 7.726-7.726 4.266 0 7.726 3.451 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.264 0-7.726-3.461-7.726-7.726zm-2.029-39.178c0-4.275 3.462-7.726 7.726-7.726 4.265 0 7.726 3.451 7.726 7.726 0 4.265-3.462 7.726-7.726 7.726-4.264.001-7.726-3.461-7.726-7.726z"/>
            <path 
              d="m430.069 83.754c0-4.265 3.451-7.726 7.726-7.726 4.265 0 7.726 3.461 7.726 7.726 0 4.265-3.462 7.726-7.726 7.726-4.275 0-7.726-3.461-7.726-7.726zm-2.266-38.941c0-4.265 3.452-7.726 7.726-7.726 4.266 0 7.726 3.461 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.274 0-7.726-3.462-7.726-7.726zm-41.207 0c0-4.265 3.452-7.726 7.726-7.726 4.266 0 7.726 3.461 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.275 0-7.726-3.462-7.726-7.726zm-41.208 0c0-4.265 3.452-7.726 7.726-7.726 4.266 0 7.726 3.461 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.274 0-7.726-3.462-7.726-7.726zm-41.207 0c0-4.265 3.452-7.726 7.716-7.726 4.276 0 7.736 3.461 7.736 7.726 0 4.265-3.461 7.726-7.736 7.726-4.264 0-7.716-3.462-7.716-7.726zm-41.207 0c0-4.265 3.452-7.726 7.726-7.726 4.266 0 7.726 3.461 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.274 0-7.726-3.462-7.726-7.726zm-41.207 0c0-4.265 3.452-7.726 7.726-7.726 4.266 0 7.726 3.461 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.275 0-7.726-3.462-7.726-7.726z"/></g></g>
        </svg>
        <span class="ml-3 text-xl">
            <a href="{% url 'landing-page' %}">DJ CRM</a>
        </span>
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center ">
        <!-- valdating which menu item in the nav to show and whhen-->
        {% if not request.user.is_authenticated %}
          <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Sign Up</a>
        {% else %}
          {% if request.user.is_organisor %}
          <a href="{% url 'agents:agent-list' %}" class="mr-5 hover:text-gray-900">Agents</a>
          {% endif %}
          <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Leads</a>
        {% endif %}
      </nav>
      {% if request.user.is_authenticated %}
        Logged in as: <strong class="ml-2">{{ request.user.username }}</strong>
        <!-- This re-solves an issue i met when loggin-out-->
          <form method="post" action="{% url 'logout' %}" class="inline">
            {% csrf_token %}
            <button type="submit" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
                Logout
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
            </button>
          </form>
        <!-- end of the resolve -->
        
        <!-- the removed code 
          <a href="{% url 'logout' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
            Logout
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
          </a>
        -->
      {% else %}
        <a href="{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
          Login
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
        </a>
      {% endif %}
    </div>
</header>

templates/scripts.html
{% load static %}


<script src="{% static 'js/main.js' %}"></script>

templates/second_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hi, Nasr</h1>
    <p>Abdullahi dheere naagtiis</p>
    <ul>
        {% for lead in leads %}
            <li>{{lead}}</li>
        {% endfor %}
    </ul>
</body>
</html>